### ISSUE TITLE
Customize menu

### ISSUE THREAD

**Issue by MegahackILoveYou** [absolllute/Mega-Hack-Pro-Future#1090] opened 2022-10-01 07:34 UTC
How do you like the idea of adding a function so that you can change the color of the menu, for example to yellow, orange and all that, as well as rainbow?

**Comment by Brittank88** [comment] 2022-10-04 16:21
Duplicate of #271

**Closed** 2022-10-04 16:24 UTC
Labels: duplicate

**Comment by MegahackILoveYou** [comment] 2022-10-05 06:48
sorry im not duplicate someone, im only want this function. sorry
