### ISSUE TITLE
"0% Practice Complete" + "Pause During Complete" Unintended Behaviour

### ISSUE THREAD

**Issue by NewAlexGamer** [absolllute/Mega-Hack-Pro-Future#324] opened 2021-12-29 22:07 UTC
if both "0% practice complete" and "pause during complete" are activated and you start practicing a level, even with deaths in the middle and using checkpoints, once you reach the end, pause during the complete animation, exit the practice mode which brings you to normal mode, it still completes the level. this means the screen starts shaking, the complete screen pops up and you can't do anything else other than pressing the 2 buttons "play again" and "exit to menu". once in the menu, the level will have the 100% completion in normal mode even if you didn't have it before, with the practice progress behaving as usual
i suggest watching this video to actually visualize it: https://www.youtube.com/watch?v=ePrnCj9Vmfk

**Comment by NewAlexGamer** [comment] 2021-12-29 22:09
wow this is a long ass title

**Comment by succmydecc** [comment] 2021-12-30 17:09
this isnt a bug, because this is normal during the end screen even if you reset it will still finish it and if you exit practice mode then it will think that you have completed in normal mode, such module exists in gdhm

**Comment by NewAlexGamer** [comment] 2021-12-30 17:45
bug or not, this shouldn't be happening

**Comment by succmydecc** [comment] 2021-12-30 21:13
this should be happening

**Comment by succmydecc** [comment] 2021-12-30 21:14
its not a bug, its a combination of two modules to make it look like a bug

**Comment by succmydecc** [comment] 2021-12-30 21:16
actually as a matter of fact, you can do the same by going to the last frame and uncheckpointing then moving one frame

**Comment by absoIute** [comment] 2021-12-30 21:18
if you hit the end portal, the level is expected to complete, that's not the bug. what's not intended is the level complete dropdown showing

**Comment by absoIute** [comment] 2022-08-23 15:16
fixed in v7.1-beta4

**Closed by absoIute** 2022-08-23 15:16 UTC
Labels: bug
