### ISSUE TITLE
Integrated GDDP

### ISSUE THREAD

**Issue by 4-Omega** [absolllute/Mega-Hack-Pro-Future#693] opened 2022-03-30 04:19 UTC
An in-game version of the GDDP that could have its tiers be separated in different menus

**Comment by NewAlexGamer** [comment] 2022-03-30 13:48
duplicate of #57

**Comment by MainConMan** [comment] 2022-03-30 14:27
> duplicate of #57

Didn't notice, Thanks! :)

**Closed by MainConMan** 2022-03-30 14:27 UTC
Labels: duplicate

**Comment by MainConMan** [comment] 2022-03-30 14:35
Duplicate of #57

**Comment by Brittank88** [comment] 2022-03-31 12:08
Duplicate of #57

**Comment by MainConMan** [comment] 2022-03-31 12:30
Duplicate of #57
