### ISSUE TITLE
Mega hack v8/v7.2 suggestion

### ISSUE THREAD

**Issue by WindowsXP70** [absolllute/Mega-Hack-Pro-Future#1159] opened 2023-01-24 19:53 UTC
I have a suggestion for a future mega hack update and its to change the ui color, cuz on v6 it was a lighter orange, on v7 its pink and on a future version i suggest to add a feature that lets you change the mega hack ui color.

**Comment by MainConMan** [comment] 2023-01-26 00:30
duplicate of #70

**Closed** 2023-01-26 00:31 UTC
