### ISSUE TITLE
Retreat Frame places the player at the wrong position (and deletes part of macro)

### ISSUE THREAD

**Issue by Spidapida** [absolllute/Mega-Hack-Pro-Future#1111] opened 2022-10-24 10:16 UTC
To reproduce:

1. Place a checkpoint.
2. Continue playing/recording the macro.
3. Toggle stepping on (or enable Frame Stepping if it was disabled, either would work)
4. Retreat some frames.
5. Restart the level (either by using in-game pause menu or MHv7), then retreat one frame.
6. You will notice that the Retreat Frame would place you at the last position you were on before the restart if you backstep a frame, instead of at the previous frame of the checkpoint.

Coincidentally, this bug also causes the part of macro to get deleted between the latest checkpoint and the current frame you are in if you are recording a macro, which is more of a side effect of the bug, instead of an actual bug.

**Comment by MainConMan** [comment] 2022-10-25 12:10
duplicate of #956

**Closed** 2022-10-25 12:11 UTC
Labels: duplicate
