### ISSUE TITLE
Noclip Percentage Death Limit

### ISSUE THREAD

**Issue by Charging45** [absolllute/Mega-Hack-Pro-Future#679] opened 2022-03-19 17:13 UTC
I think it could be useful to add an option to the noclip hack so it lets you die until a certain percentage on the level, or doesn't let you die until a certain percentage.

**Comment by MainConMan** [comment] 2022-03-19 22:08
Duplicate of #646 I think

**Comment by Charging45** [comment] 2022-03-20 04:01
> Duplicate of #646 I think

yes, didn't notice it srry

**Closed** 2022-03-22 17:20 UTC
Labels: duplicate
