### ISSUE TITLE
New Hack: Hacks Used

### ISSUE THREAD

**Issue by Squad897** [absolllute/Mega-Hack-Pro-Future#805] opened 2022-07-20 19:17 UTC
Hello, I am Squad. I would like to suggest a feature for mhv7.

Make a hack that shows a menu of hacks used upon a level completion. It would help players keep track of hacks they used when completing a level. As someone on the Demon List team, this would be very helpful as players could show us exactly what hacks they used in level completions. 

I tried my best to explain my idea, I hope it makes sense

**Comment by MainConMan** [comment] 2022-07-20 20:08
Duplicate of #787

**Comment by MainConMan** [comment] 2022-07-20 20:09
I believe this is a duplicate but if I misunderstood, feel free to reopen and correct me!

**Comment by NewAlexGamer** [comment] 2022-07-20 20:13
i don't really think this is a duplicate. what they're saying here is to make a list of hacks that were enabled/disabled during the attempt. this is different from automatically opening the menu to show what's active and what's not because it won't show if i activated noclip in the middle of the run. instead this would actually tell you that it was, maybe also adding a fancy "x% (hack) activated" format

**Comment by NewAlexGamer** [comment] 2022-07-20 20:15
but i was wondering... isn't the cheat indicator enough as proof?

**Comment by MainConMan** [comment] 2022-07-20 21:57
> i don't really think this is a duplicate. what they're saying here is to make a list of hacks that were enabled/disabled during the attempt. this is different from automatically opening the menu to show what's active and what's not because it won't show if i activated noclip in the middle of the run. instead this would actually tell you that it was, maybe also adding a fancy "x% (hack) activated" format

oh, yeah ill reopen then

**Comment by MainConMan** [comment] 2022-07-20 21:58
> but i was wondering... isn't the cheat indicator enough as proof?

it probably is but you never know

**Comment by absoIute** [comment] 2022-08-16 17:07
Cheat Indicator on endscreen solves this issue, a list of all enabled hacks would be too large to display anywhere on the endscreen

**Closed by absoIute** 2022-08-16 17:07 UTC
Labels: enhancement
