### ISSUE TITLE
Most Disliked Levels

### ISSUE THREAD

**Issue by Unspeakable-Boy** [absolllute/Mega-Hack-Pro-Future#935] opened 2022-08-12 03:56 UTC
So, there is a “Most Liked Levels” button in the search menu, and ya’ll have already added a demon and challenge list, so how about most disliked levels? Idk why, but it’s just an idea.

**Comment by NefariousIntent2** [comment] 2022-08-12 06:03
Not physically possible due to rob changing his servers to work differently. Also a duplicate I believe.

**Comment by MainConMan** [comment] 2022-08-13 18:42
Couldn't find what this is a duplicate of, but since its not possible, im gonna close this anyway

**Closed by MainConMan** 2022-08-13 18:42 UTC
