### ISSUE TITLE
Click bot for the replay system

### ISSUE THREAD

**Issue by RandomPersonXD** [absolllute/Mega-Hack-Pro-Future#1102] opened 2022-10-11 06:42 UTC
pls

**Comment by NewAlexGamer** [comment] 2022-10-11 08:04
This is like the 6th time people ask, is it that hard to read whenever absolute said no on Twitter...

**Comment by MainConMan** [comment] 2022-10-11 12:27
Duplicate of #1065

**Closed by MainConMan** 2022-10-11 12:27 UTC
