### ISSUE TITLE
Built In Autoclicker For MegaHack Replay

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#877] opened 2022-07-27 07:14 UTC
Maybe create a built an actual accurate auto clicker built into MegaHack Replay because most autoclickers are inaccurate most of the time when going through tight gaps. Examples I have found are with OmegaBot. The autoclicker is really accurate, and it works very very well.

**Comment by NewAlexGamer** [comment] 2022-07-27 08:45
#648

**Comment by MainConMan** [comment] 2022-07-27 15:40
Duplicate of #648

**Closed by MainConMan** 2022-07-27 15:40 UTC

**Comment by BrownieGamingX5** [comment] 2022-07-28 05:01
oops lol
