### ISSUE TITLE
(Keybinds) Enabling NoClip In Editior Toggles Ignore Damage

### ISSUE THREAD

**Issue by NefariousIntent2** [absolllute/Mega-Hack-Pro-Future#919] opened 2022-08-07 17:02 UTC
This would be useful if Noclip was assigned to a keybind, it would basically act like a toggler for Ignore Damage at the same time

**Comment by bruh-bruh8** [comment] 2022-08-09 00:38
i agree

**Comment by MainConMan** [comment] 2022-08-09 16:49
Duplicate of #690 i think

**Closed** 2022-08-09 16:50 UTC
Labels: duplicate
