### ISSUE TITLE
"Pause during completion" hack bug

### ISSUE THREAD

**Issue by GoldenGamerc** [absolllute/Mega-Hack-Pro-Future#870] opened 2022-07-25 23:32 UTC
so basicly, this bug is shown in this video and it's very simple.
You can pause during the completion animation, and turn on (or off) the practice mode and the level will complete itself
https://www.youtube.com/watch?v=uIlFWLZwCBQ

Also this should be tagged as a bug, but I don't use Github at all so don't blame me

**Comment by Brittank88** [comment] 2022-07-26 00:36
> Also this should be tagged as a bug, but I don't use Github at all so don't blame me

All good, you don't have permissions to add flairs to issues anyway.

**Comment by MainConMan** [comment] 2022-07-26 01:12
Duplicate of #324

**Closed by MainConMan** 2022-07-26 01:12 UTC
Labels: bug
