### ISSUE TITLE
Double Move Trigger Activation Bugfix 

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#1019] opened 2022-08-28 06:45 UTC
The bug I am talking about is the big of where a start position is on the exact same point as the move trigger, which can break a lot of stuff when playtesting with start positions. A fix for this would literally be so good to have in Geometry Dash.

**Comment by MainConMan** [comment] 2022-08-29 12:23
Duplicate of #469

**Closed** 2022-08-29 12:23 UTC
Labels: duplicate
