### ISSUE TITLE
Replay doesn't respect Start Position

### ISSUE THREAD

**Issue by getkirill** [absolllute/Mega-Hack-Pro-Future#1025] opened 2022-09-02 05:40 UTC
When you playing from start pos, replay ignores it and plays inputs like it's from 0%
Attaching 2 little snippets of what i mean (internal recorder)
[bug itself](https://youtu.be/B9tYJky4ek0)
[from 0%](https://youtu.be/q9mDgCxKzpE)

**Comment by MainConMan** [comment] 2022-09-02 12:23
Duplicate of #840

**Closed** 2022-09-02 12:25 UTC
Labels: duplicate

**Comment by getkirill** [comment] 2022-09-03 08:22
ohh, understandable
