### ISSUE TITLE
Make Hitboxes Show D, J, S, And H Blocks

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#708] opened 2022-04-09 00:31 UTC
Pretty self explanatory.

**Comment by Nicko2102** [comment] 2022-04-09 02:36
I like this idea, can be expanded from #464 pretty easily i think

**Comment by NewAlexGamer** [comment] 2022-04-09 12:33
isn't this a duplicate of #632?

**Comment by MainConMan** [comment] 2022-04-09 15:57
> isn't this a duplicate of #632?

yes it is! thanks

**Comment by MainConMan** [comment] 2022-04-09 15:57
duplicate of #632

**Closed** 2022-04-09 15:58 UTC
Labels: duplicate, enhancement

**Comment by MainConMan** [comment] 2022-04-09 16:01
Duplicate of #632
