### ISSUE TITLE
Cheat Indicator Doesn't Render With Speeds Higher Than Normal Speed

### ISSUE THREAD

**Issue by BrownieGamingX5** [absolllute/Mega-Hack-Pro-Future#920] opened 2022-08-07 23:32 UTC
I can't believe on the amount of bugs with the cheat indicator I have seen with this lmao. 

Anyways, if you have speeds higher than normal speed like 1.1x, 1.2x and higher, the cheat indicator doesn't render as you cheating, even though it technically is. Once again, it could be fixed.

**Comment by BrownieGamingX5** [comment] 2022-08-08 14:18
True. But technically, it is still cheating because you are literally making the game faster, in which you cant do without the use of hacks or mods. Even though it makes it harder, it should at-least still count for the cheat indicator.

**Comment by totallyphysicallypossible** [comment] 2022-08-12 07:02
I feel like that's an intended feature from Absolute himself, he could've just made it so enabling speedhack triggers it, but he made it in a way that it only triggers cheat indicator when it's below 1x speed.

**Comment by MainConMan** [comment] 2022-08-12 14:38
Its probably intended, if it is Absolute will just add the wont fix label

**Comment by NefariousIntent2** [comment] 2022-08-13 21:11
Heres the thing. Cheating: To gain a unfair advantage over other players. The thing is, it makes you have LESS of an advantage then regular players

**Comment by MainConMan** [comment] 2022-08-13 23:04
It's situational

**Comment by absoIute** [comment] 2022-08-16 20:38
Intended behaviour, increasing speed makes stuff harder

**Closed by absoIute** 2022-08-16 20:38 UTC
Labels: bug
