### ISSUE TITLE
Spambot

### ISSUE THREAD

**Issue by raisadesu** [absolllute/Mega-Hack-Pro-Future#823] opened 2022-07-21 09:53 UTC
I believe a spambot for MHR would be useful for botting silent levels.
It should have configurable click/release delay separately.

**Comment by sinc0s** [comment] 2022-07-21 10:05
It is planned for a future update, will probably be one of the first new additions

**Comment by NewAlexGamer** [comment] 2022-07-21 10:19
isn't this #648 ?

**Comment by Brittank88** [comment] 2022-07-21 10:30
Yes it is. Closing as duplicate of #648.

**Comment by Brittank88** [comment] 2022-07-21 10:30
Duplicate of #648

**Closed by Brittank88** 2022-07-21 10:30 UTC
